### ISSUE TITLE
文人相轻

### ISSUE THREAD

**Issue by huangbinjie** [huangbinjie/issue_blog#18]
文人相轻不只是在学术界存在，在咱们工程界甚至更严重，鄙视链是一直在更新。
之前仅凭 twitter 的一篇无限滚动的实现思路，要写出我自己的无限滚动的难度是非常巨大的，半夜失眠想怎么实现，走路的时候想怎么改设计都是经常的事，一度想放弃。我也清楚如果能做出来意味着什么，凭着这个自私的想法，终于是做出来了。
但是结果和我的期待反差太大。
国人总是对自己的同胞要求异常的严格，一边看我的代码，一边想实现成自己的东西，还不点赞...
说实话我之前也有点盲目的崇洋媚外。今后端正态度，能客观对事不对人。
希望能学好英文，眼界放到全世界。

**Comment by googya** [comment]
如果太介意某些个别人的不怀好意的批评， 否则很难走下去
