### ISSUE TITLE
已经没有勇气 `npm init` 了

### ISSUE THREAD

**Issue by huangbinjie** [huangbinjie/issue_blog#23]
累了。身心都好累。

我热爱自己的工作和公司，奈何领导和同事哎。

知道我喜欢捣鼓架构和 react，你们平时都在问我技术上的问题，结果新项目立项技术选型把我排除在外，很可以。

我承认我不是个合格的程序员，但是追求技术的心一直未变。不想大言不惭的说我比你们强，我至少适合做这个(不然你们也不会一边搭一边问我了)。既然选了 typescript 又不会用，还老是问我，我能拒绝吗。

另一方面吧，感觉同事还处在私底下互怼，互相瞧不起的层面。这是很低端的程序员的表现。其实我是很欣赏你们的，人人都有闪光点。不管你们的技术在哪个层面。但是我诚心的想你们交流技术的时候你们不想交流和说我装逼，确实难受了。

优秀的程序员应该是互相欣赏和而不同的。这里的和不是表面和气，是真诚的和气。比如互相欣赏互相吹捧，但是我用 react 你用 vue。心知肚明。

想去个大点的平台，或者至少同事都是这么优秀的平台。

想想前天又被阿里拒绝了，更难受了。

**Comment by kuitos** [comment]
> 想想前天又被阿里拒绝了
又... 这是尝试过几次...😑

**Comment by huangbinjie** [comment]
好多次....今年特别严，学历不行不好过啊。

**Comment by kuitos** [comment]
😑

**Comment by huangbinjie** [comment]
早就和领导说过，除了阿里那都不想去。。。

**Comment by huangbinjie** [comment]
@kuitos 推了几次，没过。丢人了...
